tragoudia = {
    'major' : ['Mh klais', 'Aponi Zwi', 'Sinnefiasmeni Kiriaki'],
    'minor' : ['Partides', 'Na giati pernw','Apopse Fila me','H litaneia tou magka', 'To kapileio', 'Ti paraxeni kopela',
               'Ta ziliarika sou matia', 'To kourasmeno vima sou', 'Arrwstisa sta xsena makria sou',
               'Trava re magka kai alani', 'To magkalaki', 'O monaxos o anthrwpos', 'Psilo Gazi', 'O Antwnhs o varkarhs o sereths'],
    'ousak' : ['Mpir Allax', 'O monaxos o anthrwpos', 'Pseuti ntounia', 'Sto adeio mou paketo'],
    'xitzaz' : ['Mes ton teke tis Marigws', 'As mi xsimerwne pote', 'H douleia kanei tous antres', 'To monopati',
                'Exe geia panagia', 'O pasatempos', 'Auta ta xeria'],
    'armoniko' : ['Partides', 'Eipa na svisw ta palia', 'Na giati pernw', 'Apopse Fila me', 'H litaneia tou magka','Ti paraxeni kopela',
                  'Ta ziliarika sou matia', 'To kourasmeno vima sou', 'Oloi oi rembetes tou ntounia', 'Arrwstisa sta xsena makria sou',
                  'Goissa Xsanthia', 'Ego thelw prigkhpessa', 'To magkalaki', 'Psilo Gazi'],
    'sampax' : ['O magkas tou votanikou', 'O monaxos o anthrwpos', 'H upoga', 'Sala Sala'],
    'xitzazkiar' : ['O pasatempos', 'Paraponiariko mou'],
    'niavent' : ['Rixe tsiggana ta xartia', 'O meraklis', 'Na giati pernw', 'Oloi oi rembetes tou ntounia',
                 'Ego thelw prigkhpessa', 'O Antwnhs o varkarhs o sereths', 'To minore ths aughs', 'Eimai erwteumeni me ta matia sou'],
    'kartsigiar' : ['Rixe tsiggana ta xartia'],
    'peiraiotikos' : ['Ta magemena matia sou'],
    'poimenikos' : ['O meraklis', 'Ego thelw prigkhpessa', 'Roumaniko'],
    'segiax' : ['Ta karavotsakismata'],
    'tampaxaniotikos' : ['- '],
    'xouzam' : ['Ta karavotsakismata', 'Xasisi ipie kai o theos', 'Oloi oi rembetes tou ntounia','Sth mparmparia', 'H partoudia'],
    'xouseini' : ['-'],
    'rast' : ['Xasisi ipie kai o theos', 'To xariklaki'],
    'kiournti' : ['Rixe tsiggana ta xartia', 'Arrwstisa sta xsena makria sou', 'Trava re magka kai alani', 'Karagiozis'],
    'lokrikos' : ['-'],
    'ludikos' : ['-'],
    'mixoludikos' : ['-'],
    'ouzal' : ['-'],
    'souzinak' : ['-']
}